name: Deploy Calculator

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Fix vite permission
        run: chmod +x node_modules/.bin/vite

      - name: Build project
        run: npm run build

      - name: Show built files
        run: |
          echo "ROOT:"
          pwd
          echo "DIST:"
          ls -la dist
          echo "ASSETS:"
          ls -la dist/assets
          echo "INDEX:"
          cat dist/index.html

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21 
          local-dir: ./dist/
          server-dir: /public_html/calculators/
          dangerous-clean-slate: true
           